name: CI
on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Generate distributable file
              run: make it

            - name: Validate distributable file
              run: git diff --quiet origin/${GITHUB_HEAD_REF} -- dist || { echo "Please generate distributable file using MakeFile"; exit 1;}
