name: CI
on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 2

            - name: Export distributable file
              run: make it && cat dist/all.sh

            - name: Export git diff
              run: git diff -- dist

            - name: Export git diff on current commit
              run: git diff ${{ github.sha }} -- dist

            - name: Validate distributable file
              run: make it && git diff --quiet ${{ github.sha }} -- dist || { echo "Please generate distributable file using MakeFile"; exit 1;}
